package it.unitn.lifecoach.model;

import java.io.Serializable;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;



/**
 * The persistent class for the User database table.
 * 
 */
@Entity
@Table(name="User")
@XmlRootElement
public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	/**
	 * unique identifier for this user
	 */
	@Id
	private String username;

	/**
	 * access token generated by the system while the user logs in, 
	 */
	@Column(name="access_token")
	private String accessToken;

	/**
	 * date of birth of this user
	 */
	@Column(name="date_of_birth")
	private long dateOfBirth;

	/**
	 * email of a user
	 */
	private String email;

	/**
	 * gender of a user
	 */
	private String gender;

	/**
	 * location of a user
	 */
	private String location;

	/**
	 * mobile number of a user
	 */
	@Column(name="mobile_num")
	private String mobileNum;

	/**
	 * name of a user
	 */
	private String name;

	/**
	 * password of a user
	 */
	private String password;

	/**
	 * link to profile photo of a user 
	 */
	@Column(name="profile_photo")
	private String profilePhoto;

	/**
	 * status of this account, set by the system while the user deactivates the account
	 * default: true
	 */
	private boolean status=true;


	public User() {
	}
	/** Get a unique id of a user called username 
	 * 
	 * @return username - unique id of a user
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Sets unique id of a user
	 * 
	 * @param username		unique id of a user which later used to access all information related to this user
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public long getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(long dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(String mobileNum) {
		this.mobileNum = mobileNum;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getProfilePhoto() {
		return this.profilePhoto;
	}

	public void setProfilePhoto(String profilePhoto) {
		this.profilePhoto = profilePhoto;
	}

	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Override
	public boolean equals(Object obj) {
		if(this.username==null || obj == null || !(obj instanceof User))
			return false;
		return this.username.equals(((User)obj).getUsername());
	}
}